### PR TITLE
Fix Linux paths

### PR DESCRIPTION
**Pull request by chocolateboy**
### test

```ruby
ENV['XDG_CACHE_HOME'] = '~/my-cache-dir'
EnvPaths.get('my-app', suffix: false).cache
```

### before

    ~/my-cache-dir

### after

    ~/my-cache-dir/my-app

### CODE REVIEW

**Comment by chocolateboy** [comment]
Same issue as: https://github.com/sindresorhus/env-paths/issues/5

**Comment by NickTomlin** [comment]
This seems sane. Thanks! 

It looks like rubocop is being a nuisance https://travis-ci.org/NickTomlin/env_paths/builds/291811112?utm_source=github_status&utm_medium=notification. I'd be fine with throwing a `# rubocop:disable Metrics/AbcSize` before that method (double check my syntax there by running rubocop locally)

Once that's done and the build is passing i'll merge this in. Thanks again!

**Comment by chocolateboy** [comment]
> rubocop:disable Metrics/AbcSize

I've done as you've requested, but I'm not sure why you would want that. Why enable these cops at all when they only get in the way? These tools are meant to serve us, not the other way round.

```yaml
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
```

**Comment by NickTomlin** [comment]
You make an excellent point. I think the comment is merely a stopgap until I set some saner defaults.

**Comment by NickTomlin** [comment]
This is out in https://rubygems.org/gems/env_paths/versions/1.0.0

**Comment by chocolateboy** [comment]
Thanks!

**Pull request merged**
